# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Rizal'
tagline:          'at Ruby and Rails'
description:      "The purpose of this blog is to REPOST/REBLOG blogs that I think it's IMPORTANT and I should remember it"
url:              http://rizalmuthi.com
baseurl:          /

author:
  name:           'Rizal Muthi'
  url:            https://twitter.com/rizalmuthi
  email:          'rizalmuthi@gmail.com'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
